PROJECT_SCHEMA_VERSION = "bvt-project-1"
DATASET_MANIFEST_SCHEMA_VERSION = "bvt-dataset-manifest-1"

TOOLKIT_VERSION = "0.1.0"

DEFAULT_PROJECT_NAME = "BVT Project"
DEFAULT_OUTPUT_DIRECTORY = "//bvt_output/"
DEFAULT_SEED = 12345

DEFAULT_RENDER_RESOLUTION = 512
